services:

  ms-payments:
    container_name: ms-payments
    build:
      context: .
      args:
        - APP=ms-payments
    restart: always
    ports:
      - "3001:3000"
      - "50051:50051"
    volumes:
      - .:/usr/src/app

  ms-products:
    container_name: ms-products
    build:
      context: .
      args:
        - APP=ms-products
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
  