/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace payments {
    export interface PaymentService {
        payOrder(
            data: PayOrderRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<PayOrderResponse>;
    }
    export interface PayOrderRequest {
        value?: number;
        cpf?: string;
        cardNumber?: string;
    }
    export interface PayOrderResponse {
        success?: boolean;
        message?: string;
    }
}

